use std::str::FromStr;

/// Virtual (semantic value) of key.
/// Mostly equal to a key code if non-latin layout is in use.
/// MOstly equal to text representation if latin layout is in use.
enum VirtualKey {
    //Letters
    VKeyA,
    VKeyB,
    VKeyC,
    VKeyD,
    VKeyE,
    VKeyF,
    VKeyG,
    VKeyH,
    VKeyI,
    VKeyJ,
    VKeyK,
    VKeyL,
    VKeyM,
    VKeyN,
    VKeyO,
    VKeyP,
    VKeyQ,
    VKeyR,
    VKeyS,
    VKeyT,
    VKeyU,
    VKeyV,
    VKeyW,
    VKeyX,
    VKeyY,
    VKeyZ,

    //Numbers
    VKey0,
    VKey1,
    VKey2,
    VKey3,
    VKey4,
    VKey5,
    VKey6,
    VKey7,
    VKey8,
    VKey9,

    //Functional
    VKeyF1,
    VKeyF2,
    VKeyF3,
    VKeyF4,
    VKeyF5,
    VKeyF6,
    VKeyF7,
    VKeyF8,
    VKeyF9,
    VKeyF10,
    VKeyF11,
    VKeyF12,
    VKeyF13,
    VKeyF14,
    VKeyF15,
    VKeyF16,
    VKeyF17,
    VKeyF18,
    VKeyF19,
    VKeyF20,
    VKeyF21,
    VKeyF22,
    VKeyF23,
    VKeyF24,
    VKeyF25,
    VKeyF26,
    VKeyF27,
    VKeyF28,
    VKeyF29,
    VKeyF30,

    //Cursor
    VKeyUp,
    VKeyDown,
    VKeyLeft,
    VKeyRight,
    VKeyHome,
    VKeyEnd,
    VKeyPageUp,
    VKeyPageDown,
    VKeyDelete,
    VKeyInsert,
    VKeyBackSpace,
    VKeyEnter,
    VKeyTab,

    //Symbols
    VKeyBackquote,
    VKeyBackslash,
    VKeyBracketLeft,
    VKeyBracketRight,
    VKeyComma,
    VKeyEqual,
    VKeyMinus,
    VKeyPeriod,
    VKeyQuote,
    VKeySemicolon,
    VKeySlash,
    VKeyPlus,
    VKeyMultiply,

    // Control
    VKeyEscape,
    VKeyAlt,
    VKeyControl,
    VKeyShift,
    VKeySuper,

    VKeyLeftAlt,
    VKeyLeftControl,
    VKeyLeftShift,
    VKeyLeftSuper,

    VKeyRightAlt,
    VKeyRightControl,
    VKeyRightShift,
    VKeyRightSuper,
}

impl FromStr for VirtualKey {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s {
            "a" => VirtualKey::VKeyA,
            "b" => VirtualKey::VKeyB,
            "c" => VirtualKey::VKeyC,
            "d" => VirtualKey::VKeyD,
            "e" => VirtualKey::VKeyE,
            "f" => VirtualKey::VKeyF,
            "g" => VirtualKey::VKeyG,
            "h" => VirtualKey::VKeyH,
            "i" => VirtualKey::VKeyI,
            "j" => VirtualKey::VKeyJ,
            "k" => VirtualKey::VKeyK,
            "l" => VirtualKey::VKeyL,
            "m" => VirtualKey::VKeyM,
            "n" => VirtualKey::VKeyN,
            "o" => VirtualKey::VKeyO,
            "p" => VirtualKey::VKeyP,
            "q" => VirtualKey::VKeyQ,
            "r" => VirtualKey::VKeyR,
            "s" => VirtualKey::VKeyS,
            "t" => VirtualKey::VKeyT,
            "u" => VirtualKey::VKeyU,
            "v" => VirtualKey::VKeyV,
            "w" => VirtualKey::VKeyW,
            "x" => VirtualKey::VKeyX,
            "y" => VirtualKey::VKeyY,
            "z" => VirtualKey::VKeyZ,
            "=" => VirtualKey::VKeyEqual,
            "-" => VirtualKey::VKeyMinus,
            "0" => VirtualKey::VKey0,
            "1" => VirtualKey::VKey1,
            "2" => VirtualKey::VKey2,
            "3" => VirtualKey::VKey3,
            "4" => VirtualKey::VKey4,
            "5" => VirtualKey::VKey5,
            "6" => VirtualKey::VKey6,
            "7" => VirtualKey::VKey7,
            "8" => VirtualKey::VKey8,
            "9" => VirtualKey::VKey9,
            "`" => VirtualKey::VKeyBackquote,
            "/" => VirtualKey::VKeySlash,
            "\\" => VirtualKey::VKeyBackslash,
            "," => VirtualKey::VKeyComma,
            "." => VirtualKey::VKeyPeriod,
            "*" => VirtualKey::VKeyMultiply,
            "+" => VirtualKey::VKeyPlus,
            ";" => VirtualKey::VKeySemicolon,
            "'" => VirtualKey::VKeyQuote,
            "[" => VirtualKey::VKeyBracketLeft,
            "]" => VirtualKey::VKeyBracketRight,
            "f1" => VirtualKey::VKeyF1,
            "f2" => VirtualKey::VKeyF2,
            "f3" => VirtualKey::VKeyF3,
            "f4" => VirtualKey::VKeyF4,
            "f5" => VirtualKey::VKeyF5,
            "f6" => VirtualKey::VKeyF6,
            "f7" => VirtualKey::VKeyF7,
            "f8" => VirtualKey::VKeyF8,
            "f9" => VirtualKey::VKeyF9,
            "f10" => VirtualKey::VKeyF10,
            "f11" => VirtualKey::VKeyF11,
            "f12" => VirtualKey::VKeyF12,
            "f13" => VirtualKey::VKeyF13,
            "f14" => VirtualKey::VKeyF14,
            "f15" => VirtualKey::VKeyF15,
            "f16" => VirtualKey::VKeyF16,
            "f17" => VirtualKey::VKeyF17,
            "f18" => VirtualKey::VKeyF18,
            "f19" => VirtualKey::VKeyF19,
            "f20" => VirtualKey::VKeyF20,
            "f21" => VirtualKey::VKeyF21,
            "f22" => VirtualKey::VKeyF22,
            "f23" => VirtualKey::VKeyF23,
            "f24" => VirtualKey::VKeyF24,
            "f25" => VirtualKey::VKeyF25,
            "f26" => VirtualKey::VKeyF26,
            "f27" => VirtualKey::VKeyF27,
            "f28" => VirtualKey::VKeyF28,
            "f29" => VirtualKey::VKeyF29,
            "f30" => VirtualKey::VKeyF30,

            "up" => VirtualKey::VKeyUp,
            "down" => VirtualKey::VKeyDown,
            "left" => VirtualKey::VKeyLeft,
            "right" => VirtualKey::VKeyRight,

            "end" => VirtualKey::VKeyEnd,
            "home" => VirtualKey::VKeyHome,
            "pageup" => VirtualKey::VKeyPageUp,
            "pagedown" => VirtualKey::VKeyPageDown,
            "delete" => VirtualKey::VKeyDelete,
            "insert" => VirtualKey::VKeyInsert,
            "tab" => VirtualKey::VKeyTab,
            "backspace" => VirtualKey::VKeyBackSpace,
            "enter" => VirtualKey::VKeyEnter,

            "escape" => VirtualKey::VKeyEscape,
            "alt" => VirtualKey::VKeyAlt,
            "control" => VirtualKey::VKeyControl,
            "ctrl" => VirtualKey::VKeyControl,
            "shift" => VirtualKey::VKeyShift,
            "super" => VirtualKey::VKeySuper,

            "lalt" => VirtualKey::VKeyLeftAlt,
            "lcontrol" => VirtualKey::VKeyLeftControl,
            "lctrl" => VirtualKey::VKeyLeftControl,
            "lshift" => VirtualKey::VKeyLeftShift,
            "lsuper" => VirtualKey::VKeyLeftSuper,

            "ralt" => VirtualKey::VKeyRightAlt,
            "rcontrol" => VirtualKey::VKeyRightControl,
            "rctrl" => VirtualKey::VKeyRightControl,
            "rshift" => VirtualKey::VKeyRightShift,
            "rsuper" => VirtualKey::VKeyRightSuper,
            _ => return Err(()),
        })
    }
}
