white = "#d5c4a1"
black = "#282828"
grey = "#32302f"
light_grey = "#665c54"
blue = "#458588"
red = "#cc241d"
yellow = "#d69921"
orange = "#d65d0e"
green = "#98971a"
purple = "#b16286"
cyan = "#689d6a"
magenta = "#bf7280"

"lapce.active_tab" = "$black"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#000000"
"lapce.scroll_bar" = "$grey"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "$black"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "#3B8085"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#545862"

"editor.background" = "#1d2021"
"editor.foreground" = "$white"
"editor.dim" = "#5C6370"
"editor.focus" = "#CCCCCC"
"editor.caret" = "#528bff"
"editor.selection" = "$light_grey"
"editor.current_line" = "$grey"

"source_control.added" = "#50a14f32"
"source_control.removed" = "#ff526632"
"source_control.modified" = "#0184bc32"

"palette.background" = "#383838"
"palette.current" = "7c6f64"

"completion.background" = "#ebdbb2"
"completion.current" = "#282828"

"panel.background" = "101514"
"panel.current" = "$grey"

"status.background" = "#a89984"

"style.comment" = "#504945"

"style.constant" = "$yellow"
"style.type" = "$yellow"
"style.typeAlias" = "$yellow"
"style.number" = "$yellow"
"style.enum" = "$yellow"
"style.struct" = "$yellow"
"style.structure" = "$yellow"
"style.interface" = "$yellow"
"style.attribute" = "$yellow"
"style.constructor" = "$yellow"

"style.function" = "$blue"
"style.method" = "$blue"
"style.function.method" = "$blue"

"style.keyword" = "$purple"
"style.selfKeyword" = "$purple"

"style.field" = "$red"
"style.property" = "$red"
"style.enumMember" = "$red"
"style.enum-member" = "$red"
"style.variable.other.member" = "$red"

"style.string" = "$green"

"style.type.builtin" = "$cyan"
"style.builtinType" = "$cyan"
"style.escape" = "$cyan"
"style.embedded" = "$cyan"
